name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo ${{ github.event.client_payload.sha }}

      - run: |
          # print in json github.event
          echo "${{ toJson(github.event) }}"