# Reusable GitHub Actions workflow for Scribe evidence job

name: .scribe-in-pipeline-scan

on:
  workflow_call:
    secrets:
      SCRIBE_TOKEN:
        required: false
    inputs:
      target:
        type: string
        required: false

jobs:
  scribe-scan:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            repository: scribe-security/compliance
            ref: main

      - run: |
          ls -lh
          printenv



      # if target is not provided, issue valint directly on the traget.
      - name:  Target Image, Src, Generate BOM abd SLSA, upload to scribe
        if : ${{ !inputs.target }}
        id: bom_image_tag
        uses: scribe-security/action-bom@dev
        with:
          target: ${{ inputs.target }}
          input: git:.
          provenance: true
          verbose: 2
          format: attest
          filter-regex: ./**/test/**/
          scribe-client-secret: ${{ secrets.SCRIBE_TOKEN }}
          
          # product-key: valint
          # product-version: ${{ env.version }}
         