# Reusable GitHub Actions workflow for Scribe evidence job

name: .scribe-in-pipeline-scan

on:
  workflow_call:
    secrets:
      SCRIBE_TOKEN:
        required: false
    inputs:
      target:
        type: string
        required: false

jobs:
  scribe-scan:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            path: target_repo

      - run: |
          ls -lh
          printenv

      - name:  Get Platforms Scope
        run: |
          source target_repo/.github/workflows/context
          printenv | grep SCRIBE_CONTEXT
          


      # # if target is provided, scan the target
      # - name:  Target Image, Src, Generate BOM abd SLSA, upload to scribe
      #   if : ${{ inputs.target }}
      #   id: bom_image_tag
      #   uses: scribe-security/action-bom@dev
      #   with:
      #     target: ${{ inputs.target }}
      #     input: git:./target_repo
      #     provenance: true
      #     verbose: 2
      #     filter-regex: ./**/test/**/
      #     scribe-client-secret: ${{ secrets.SCRIBE_TOKEN }}

      #     # product-key: valint
      #     # product-version: ${{ env.version }}
         